// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgniOop3f_dBwhBAdZKaU2bYzT0lstMls',
    appId: '1:906988176481:web:450568d1044f9800b8d620',
    messagingSenderId: '906988176481',
    projectId: 'flutters-44285',
    authDomain: 'flutters-44285.firebaseapp.com',
    storageBucket: 'flutters-44285.appspot.com',
    measurementId: 'G-4MXHJKE541',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXIKsaVZg65aGdJFK_Br2HL3R88pXk1OI',
    appId: '1:906988176481:android:577882a26bdc5bebb8d620',
    messagingSenderId: '906988176481',
    projectId: 'flutters-44285',
    storageBucket: 'flutters-44285.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgwDJG3nFWk9-Z7JbSwgA9z4G99kZLpC8',
    appId: '1:906988176481:ios:f41a2dbdfe5c070ab8d620',
    messagingSenderId: '906988176481',
    projectId: 'flutters-44285',
    storageBucket: 'flutters-44285.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgwDJG3nFWk9-Z7JbSwgA9z4G99kZLpC8',
    appId: '1:906988176481:ios:cbe117c992705b6fb8d620',
    messagingSenderId: '906988176481',
    projectId: 'flutters-44285',
    storageBucket: 'flutters-44285.appspot.com',
    iosBundleId: 'com.example.app.RunnerTests',
  );
}
